import React, { useMemo } from 'react';
import Select from 'react-select';

// قائمة بمدن العالم الرئيسية
const worldCities = [

  
  // الإمارات
  { value: 'دبي', label: 'دبي (Dubai)' },
  { value: 'أبوظبي', label: 'أبوظبي (Abu Dhabi)' },
  { value: 'الشارقة', label: 'الشارقة (Sharjah)' },
  { value: 'عجمان', label: 'عجمان (Ajman)' },
  { value: 'رأس الخيمة', label: 'رأس الخيمة (Ras Al Khaimah)' },
  { value: 'الفجيرة', label: 'الفجيرة (Fujairah)' },
  { value: 'أم القيوين', label: 'أم القيوين (Umm Al Quwain)' },
  
  // الكويت
  { value: 'الكويت', label: 'الكويت (Kuwait City)' },
  { value: 'السالمية', label: 'السالمية (Salmiya)' },
  { value: 'الجهراء', label: 'الجهراء (Al Jahra)' },
  
  // قطر
  { value: 'الدوحة', label: 'الدوحة (Doha)' },
  { value: 'الريان', label: 'الريان (Al Rayyan)' },
  { value: 'الوكرة', label: 'الوكرة (Al Wakrah)' },
  
  // البحرين
  { value: 'المنامة', label: 'المنامة (Manama)' },
  { value: 'المحرق', label: 'المحرق (Muharraq)' },
  { value: 'الرفاع', label: 'الرفاع (Riffa)' },
  
  // عمان
  { value: 'مسقط', label: 'مسقط (Muscat)' },
  { value: 'صلالة', label: 'صلالة (Salalah)' },
  { value: 'صور', label: 'صور (Sur)' },
  
  // الأردن
  { value: 'عمان', label: 'عمان (Amman)' },
  { value: 'إربد', label: 'إربد (Irbid)' },
  { value: 'الزرقاء', label: 'الزرقاء (Az Zarqa)' },
  
  // لبنان
  { value: 'بيروت', label: 'بيروت (Beirut)' },
  { value: 'طرابلس', label: 'طرابلس (Tripoli)' },
  { value: 'صيدا', label: 'صيدا (Sidon)' },
  
  // سوريا
  { value: 'دمشق', label: 'دمشق (Damascus)' },
  { value: 'حلب', label: 'حلب (Aleppo)' },
  { value: 'حمص', label: 'حمص (Homs)' },
  
  // العراق
  { value: 'بغداد', label: 'بغداد (Baghdad)' },
  { value: 'البصرة', label: 'البصرة (Basra)' },
  { value: 'الموصل', label: 'الموصل (Mosul)' },
  { value: 'أربيل', label: 'أربيل (Erbil)' },
  
  // اليمن
  { value: 'صنعاء', label: 'صنعاء (Sana\'a)' },
  { value: 'عدن', label: 'عدن (Aden)' },
  { value: 'تعز', label: 'تعز (Taiz)' },
  
  // أفريقيا
  { value: 'الدار البيضاء', label: 'الدار البيضاء (Casablanca)' },
  { value: 'الرباط', label: 'الرباط (Rabat)' },
  { value: 'فاس', label: 'فاس (Fes)' },
  { value: 'مراكش', label: 'مراكش (Marrakech)' },
  { value: 'طنجة', label: 'طنجة (Tangier)' },
  { value: 'أغادير', label: 'أغادير (Agadir)' },
  { value: 'مكناس', label: 'مكناس (Meknes)' },
  { value: 'تونس', label: 'تونس (Tunis)' },
  { value: 'صفاقس', label: 'صفاقس (Sfax)' },
  { value: 'سوسة', label: 'سوسة (Sousse)' },
  { value: 'الجزائر', label: 'الجزائر (Algiers)' },
  { value: 'وهران', label: 'وهران (Oran)' },
  { value: 'قسنطينة', label: 'قسنطينة (Constantine)' },
  { value: 'عنابة', label: 'عنابة (Annaba)' },
  { value: 'طرابلس', label: 'طرابلس - ليبيا (Tripoli)' },
  { value: 'بنغازي', label: 'بنغازي (Benghazi)' },
  { value: 'الخرطوم', label: 'الخرطوم (Khartoum)' },
  { value: 'بورتسودان', label: 'بورتسودان (Port Sudan)' },
  { value: 'نيروبي', label: 'نيروبي (Nairobi)' },
  { value: 'مومباسا', label: 'مومباسا (Mombasa)' },
  { value: 'كيسومو', label: 'كيسومو (Kisumu)' },
  { value: 'جوهانسبرغ', label: 'جوهانسبرغ (Johannesburg)' },
  { value: 'كيب تاون', label: 'كيب تاون (Cape Town)' },
  { value: 'ديربان', label: 'ديربان (Durban)' },
  { value: 'بريتوريا', label: 'بريتوريا (Pretoria)' },
  { value: 'لاغوس', label: 'لاغوس (Lagos)' },
  { value: 'كانو', label: 'كانو (Kano)' },
  { value: 'إيبادان', label: 'إيبادان (Ibadan)' },
  { value: 'أبوجا', label: 'أبوجا (Abuja)' },
  { value: 'أكرا', label: 'أكرا (Accra)' },
  { value: 'كيب كوست', label: 'كيب كوست (Cape Coast)' },
  { value: 'داكار', label: 'داكار (Dakar)' },
  { value: 'أبيدجان', label: 'أبيدجان (Abidjan)' },
  { value: 'أديس أبابا', label: 'أديس أبابا (Addis Ababa)' },
  { value: 'دار السلام', label: 'دار السلام (Dar es Salaam)' },
  { value: 'أروشا', label: 'أروشا (Arusha)' },
  { value: 'كمبالا', label: 'كمبالا (Kampala)' },
  { value: 'كيغالي', label: 'كيغالي (Kigali)' },
  { value: 'لواندا', label: 'لواندا (Luanda)' },
  { value: 'لوساكا', label: 'لوساكا (Lusaka)' },





  { value: 'هراري', label: 'هراري (Harare)' },
  { value: 'غابورون', label: 'غابورون (Gaborone)' },
  { value: 'ويندهوك', label: 'ويندهوك (Windhoek)' },
  

























  // مصر
  { value: 'القاهرة', label: 'القاهرة (Cairo)' },
  { value: 'الإسكندرية', label: 'الإسكندرية (Alexandria)' },
  { value: 'الجيزة', label: 'الجيزة (Giza)' },
  { value: 'شبرا الخيمة', label: 'شبرا الخيمة (Shubra El Kheima)' },
  { value: 'بورسعيد', label: 'بورسعيد (Port Said)' },
  { value: 'السويس', label: 'السويس (Suez)' },
  { value: 'الأقصر', label: 'الأقصر (Luxor)' },
  { value: 'أسوان', label: 'أسوان (Aswan)' },
  { value: 'طنطا', label: 'طنطا (Tanta)' },
  { value: 'المنصورة', label: 'المنصورة (Mansoura)' },
  { value: 'أسيوط', label: 'أسيوط (Asyut)' },
  { value: 'الإسماعيلية', label: 'الإسماعيلية (Ismailia)' },
  { value: 'دمياط', label: 'دمياط (Damietta)' },
  { value: 'الزقازيق', label: 'الزقازيق (Zagazig)' },
  { value: 'قنا', label: 'قنا (Qena)' },
  { value: 'سوهاج', label: 'سوهاج (Sohag)' },
  { value: 'بنها', label: 'بنها (Benha)' },
  { value: 'كفر الشيخ', label: 'كفر الشيخ (Kafr El Sheikh)' },
  { value: 'دمنهور', label: 'دمنهور (Damanhur)' },
  { value: 'المنيا', label: 'المنيا (Minya)' },
  { value: 'بني سويف', label: 'بني سويف (Beni Suef)' },
  { value: 'شبين الكوم', label: 'شبين الكوم (Shibin El Kom)' },
  { value: 'مرسى مطروح', label: 'مرسى مطروح (Marsa Matruh)' },
  { value: 'العريش', label: 'العريش (Arish)' },
  { value: 'الفيوم', label: 'الفيوم (Faiyum)' },



  // آسيا
  { value: 'إسطنبول', label: 'إسطنبول (Istanbul)' },
  { value: 'أنقرة', label: 'أنقرة (Ankara)' },
  { value: 'إزمير', label: 'إزمير (Izmir)' },
  { value: 'بورصة', label: 'بورصة (Bursa)' },
  { value: 'أنطاليا', label: 'أنطاليا (Antalya)' },
  { value: 'غازي عنتاب', label: 'غازي عنتاب (Gaziantep)' },
  { value: 'قونية', label: 'قونية (Konya)' },
  { value: 'طهران', label: 'طهران (Tehran)' },
  { value: 'مشهد', label: 'مشهد (Mashhad)' },
  { value: 'إصفهان', label: 'إصفهان (Isfahan)' },
  { value: 'شيراز', label: 'شيراز (Shiraz)' },
  { value: 'تبريز', label: 'تبريز (Tabriz)' },
  { value: 'قم', label: 'قم (Qom)' },
  { value: 'أهواز', label: 'أهواز (Ahvaz)' },
  { value: 'كرمانشاه', label: 'كرمانشاه (Kermanshah)' },
  { value: 'كابل', label: 'كابل (Kabul)' },
  { value: 'قندهار', label: 'قندهار (Kandahar)' },
  { value: 'مزار شريف', label: 'مزار شريف (Mazar-i-Sharif)' },
  { value: 'إسلام أباد', label: 'إسلام أباد (Islamabad)' },
  { value: 'كراتشي', label: 'كراتشي (Karachi)' },
  { value: 'لاهور', label: 'لاهور (Lahore)' },
  { value: 'فيصل آباد', label: 'فيصل آباد (Faisalabad)' },
  { value: 'راولبندي', label: 'راولبندي (Rawalpindi)' },
  { value: 'ملتان', label: 'ملتان (Multan)' },
  { value: 'بيشاور', label: 'بيشاور (Peshawar)' },
  { value: 'كويتا', label: 'كويتا (Quetta)' },
  { value: 'دكا', label: 'دكا (Dhaka)' },
  { value: 'شيتاغونغ', label: 'شيتاغونغ (Chittagong)' },
  { value: 'كولكاتا', label: 'كولكاتا (Kolkata)' },
  { value: 'مومباي', label: 'مومباي (Mumbai)' },
  { value: 'دلهي', label: 'دلهي (Delhi)' },
  { value: 'بنغالور', label: 'بنغالور (Bangalore)' },
  { value: 'تشيناي', label: 'تشيناي (Chennai)' },
  { value: 'حيدر أباد', label: 'حيدر أباد (Hyderabad)' },
  { value: 'أحمد أباد', label: 'أحمد أباد (Ahmedabad)' },
  { value: 'بونه', label: 'بونه (Pune)' },
  { value: 'سورت', label: 'سورت (Surat)' },
  { value: 'كانبور', label: 'كانبور (Kanpur)' },
  { value: 'جايبور', label: 'جايبور (Jaipur)' },
  { value: 'لكناو', label: 'لكناو (Lucknow)' },
  { value: 'ناغبور', label: 'ناغبور (Nagpur)' },
  { value: 'باتنا', label: 'باتنا (Patna)' },
  { value: 'إندور', label: 'إندور (Indore)' },
  { value: 'فادودارا', label: 'فادودارا (Vadodara)' },
  { value: 'غازي أباد', label: 'غازي أباد (Ghaziabad)' },
  { value: 'كوتشي', label: 'كوتشي (Kochi)' },
  { value: 'كولومبو', label: 'كولومبو (Colombo)' },
  { value: 'كاندي', label: 'كاندي (Kandy)' },
  { value: 'كوالالمبور', label: 'كوالالمبور (Kuala Lumpur)' },
  { value: 'جورج تاون', label: 'جورج تاون (George Town)' },
  { value: 'جوهور بهرو', label: 'جوهور بهرو (Johor Bahru)' },
  { value: 'إيبوه', label: 'إيبوه (Ipoh)' },
  { value: 'ملقا', label: 'ملقا (Malacca)' },
  { value: 'سنغافورة', label: 'سنغافورة (Singapore)' },
  { value: 'جاكرتا', label: 'جاكرتا (Jakarta)' },
  { value: 'سورابايا', label: 'سورابايا (Surabaya)' },
  { value: 'باندونغ', label: 'باندونغ (Bandung)' },
  { value: 'ميدان', label: 'ميدان (Medan)' },
  { value: 'سيمارانغ', label: 'سيمارانغ (Semarang)' },
  { value: 'ماكاسار', label: 'ماكاسار (Makassar)' },
  { value: 'بالانغكارايا', label: 'بالانغكارايا (Palangka Raya)' },
  { value: 'بانكوك', label: 'بانكوك (Bangkok)' },
  { value: 'نونثابوري', label: 'نونثابوري (Nonthaburi)' },
  { value: 'باتايا', label: 'باتايا (Pattaya)' },
  { value: 'تشيانغ ماي', label: 'تشيانغ ماي (Chiang Mai)' },
  { value: 'هات ياي', label: 'هات ياي (Hat Yai)' },
  { value: 'هانوي', label: 'هانوي (Hanoi)' },
  { value: 'هو تشي منه', label: 'هو تشي منه (Ho Chi Minh City)' },
  { value: 'دا نانغ', label: 'دا نانغ (Da Nang)' },
  { value: 'هاي فونغ', label: 'هاي فونغ (Hai Phong)' },
  { value: 'كان ثو', label: 'كان ثو (Can Tho)' },
  { value: 'مانيلا', label: 'مانيلا (Manila)' },
  { value: 'كيزون سيتي', label: 'كيزون سيتي (Quezon City)' },
  { value: 'كالوكان', label: 'كالوكان (Caloocan)' },
  { value: 'دافاو', label: 'دافاو (Davao)' },
  { value: 'سيبو', label: 'سيبو (Cebu)' },
  { value: 'زامبوانغا', label: 'زامبوانغا (Zamboanga)' },
  { value: 'أنتيبولو', label: 'أنتيبولو (Antipolo)' },
  { value: 'سيول', label: 'سيول (Seoul)' },
  { value: 'بوسان', label: 'بوسان (Busan)' },
  { value: 'إنتشون', label: 'إنتشون (Incheon)' },
  { value: 'دايجو', label: 'دايجو (Daegu)' },
  { value: 'دايجون', label: 'دايجون (Daejeon)' },
  { value: 'غوانغجو', label: 'غوانغجو (Gwangju)' },
  { value: 'أولسان', label: 'أولسان (Ulsan)' },
  { value: 'سوون', label: 'سوون (Suwon)' },
  { value: 'طوكيو', label: 'طوكيو (Tokyo)' },
  { value: 'أوساكا', label: 'أوساكا (Osaka)' },
  { value: 'كيوتو', label: 'كيوتو (Kyoto)' },
  { value: 'يوكوهاما', label: 'يوكوهاما (Yokohama)' },
  { value: 'ناغويا', label: 'ناغويا (Nagoya)' },
  { value: 'سابورو', label: 'سابورو (Sapporo)' },
  { value: 'فوكوكا', label: 'فوكوكا (Fukuoka)' },
  { value: 'كوبي', label: 'كوبي (Kobe)' },
  { value: 'كاواساكي', label: 'كاواساكي (Kawasaki)' },
  { value: 'سايتاما', label: 'سايتاما (Saitama)' },
  { value: 'هيروشيما', label: 'هيروشيما (Hiroshima)' },
  { value: 'سنداي', label: 'سنداي (Sendai)' },
  { value: 'كيتاكيوشو', label: 'كيتاكيوشو (Kitakyushu)' },
  { value: 'بكين', label: 'بكين (Beijing)' },
  { value: 'شنغهاي', label: 'شنغهاي (Shanghai)' },
  { value: 'غوانغتشو', label: 'غوانغتشو (Guangzhou)' },
  { value: 'شينزين', label: 'شينزين (Shenzhen)' },
  { value: 'تشونغتشينغ', label: 'تشونغتشينغ (Chongqing)' },
  { value: 'تشنغدو', label: 'تشنغدو (Chengdu)' },
  { value: 'تيانجين', label: 'تيانجين (Tianjin)' },
  { value: 'ووهان', label: 'ووهان (Wuhan)' },
  { value: 'شيان', label: 'شيان (Xi\'an)' },
  { value: 'نانجينغ', label: 'نانجينغ (Nanjing)' },
  { value: 'هانغتشو', label: 'هانغتشو (Hangzhou)' },
  { value: 'دونغوان', label: 'دونغوان (Dongguan)' },
  { value: 'فوشان', label: 'فوشان (Foshan)' },
  { value: 'جينان', label: 'جينان (Jinan)' },
  { value: 'داليان', label: 'داليان (Dalian)' },
  { value: 'تشينغداو', label: 'تشينغداو (Qingdao)' },
  { value: 'هاربين', label: 'هاربين (Harbin)' },
  { value: 'تشانغشا', label: 'تشانغشا (Changsha)' },
  { value: 'شنيانغ', label: 'شنيانغ (Shenyang)' },
  { value: 'كونمينغ', label: 'كونمينغ (Kunming)' },
  { value: 'تشانغتشون', label: 'تشانغتشون (Changchun)' },
  { value: 'شيجياتشوانغ', label: 'شيجياتشوانغ (Shijiazhuang)' },
  { value: 'تاييوان', label: 'تاييوان (Taiyuan)' },
  { value: 'هونغ كونغ', label: 'هونغ كونغ (Hong Kong)' },
  { value: 'تايبي', label: 'تايبي (Taipei)' },
  { value: 'كاوهسيونغ', label: 'كاوهسيونغ (Kaohsiung)' },
  { value: 'تايتشونغ', label: 'تايتشونغ (Taichung)' },
  { value: 'تاي نان', label: 'تاي نان (Tainan)' },
  
  // أوروبا
  { value: 'لندن', label: 'لندن (London)' },
  { value: 'برمنغهام', label: 'برمنغهام (Birmingham)' },
  { value: 'مانشستر', label: 'مانشستر (Manchester)' },
  { value: 'ليفربول', label: 'ليفربول (Liverpool)' },
  { value: 'ليدز', label: 'ليدز (Leeds)' },
  { value: 'شيفيلد', label: 'شيفيلد (Sheffield)' },
  { value: 'إدنبرة', label: 'إدنبرة (Edinburgh)' },
  { value: 'غلاسكو', label: 'غلاسكو (Glasgow)' },
  { value: 'بلفاست', label: 'بلفاست (Belfast)' },
  { value: 'كارديف', label: 'كارديف (Cardiff)' },
  { value: 'باريس', label: 'باريس (Paris)' },
  { value: 'ليون', label: 'ليون (Lyon)' },
  { value: 'مرسيليا', label: 'مرسيليا (Marseille)' },
  { value: 'تولوز', label: 'تولوز (Toulouse)' },
  { value: 'نيس', label: 'نيس (Nice)' },
  { value: 'نانت', label: 'نانت (Nantes)' },
  { value: 'ستراسبورغ', label: 'ستراسبورغ (Strasbourg)' },
  { value: 'مونبلييه', label: 'مونبلييه (Montpellier)' },
  { value: 'بوردو', label: 'بوردو (Bordeaux)' },
  { value: 'ليل', label: 'ليل (Lille)' },
  { value: 'برلين', label: 'برلين (Berlin)' },
  { value: 'هامبورغ', label: 'هامبورغ (Hamburg)' },
  { value: 'ميونخ', label: 'ميونخ (Munich)' },
  { value: 'كولونيا', label: 'كولونيا (Cologne)' },
  { value: 'فرانكفورت', label: 'فرانكفورت (Frankfurt)' },
  { value: 'شتوتغارت', label: 'شتوتغارت (Stuttgart)' },
  { value: 'دوسلدورف', label: 'دوسلدورف (Düsseldorf)' },
  { value: 'دورتموند', label: 'دورتموند (Dortmund)' },
  { value: 'إيسن', label: 'إيسن (Essen)' },
  { value: 'لايبزيغ', label: 'لايبزيغ (Leipzig)' },
  { value: 'بريمن', label: 'بريمن (Bremen)' },
  { value: 'درسدن', label: 'درسدن (Dresden)' },
  { value: 'هانوفر', label: 'هانوفر (Hanover)' },
  { value: 'نورمبرغ', label: 'نورمبرغ (Nuremberg)' },
  { value: 'روما', label: 'روما (Rome)' },
  { value: 'ميلانو', label: 'ميلانو (Milan)' },
  { value: 'نابولي', label: 'نابولي (Naples)' },
  { value: 'تورينو', label: 'تورينو (Turin)' },
  { value: 'باليرمو', label: 'باليرمو (Palermo)' },
  { value: 'جنوة', label: 'جنوة (Genoa)' },
  { value: 'بولونيا', label: 'بولونيا (Bologna)' },
  { value: 'فلورنسا', label: 'فلورنسا (Florence)' },
  { value: 'باري', label: 'باري (Bari)' },
  { value: 'كاتانيا', label: 'كاتانيا (Catania)' },
  { value: 'البندقية', label: 'البندقية (Venice)' },
  { value: 'فيرونا', label: 'فيرونا (Verona)' },
  { value: 'مدريد', label: 'مدريد (Madrid)' },
  { value: 'برشلونة', label: 'برشلونة (Barcelona)' },
  { value: 'بلنسية', label: 'بلنسية (Valencia)' },
  { value: 'إشبيلية', label: 'إشبيلية (Seville)' },
  { value: 'سرقسطة', label: 'سرقسطة (Zaragoza)' },
  { value: 'مالقة', label: 'مالقة (Málaga)' },
  { value: 'مورسيا', label: 'مورسيا (Murcia)' },
  { value: 'بالما', label: 'بالما (Palma)' },
  { value: 'لاس بالماس', label: 'لاس بالماس (Las Palmas)' },
  { value: 'بلباو', label: 'بلباو (Bilbao)' },
  { value: 'أمستردام', label: 'أمستردام (Amsterdam)' },
  { value: 'روتردام', label: 'روتردام (Rotterdam)' },
  { value: 'لاهاي', label: 'لاهاي (The Hague)' },
  { value: 'أوتريخت', label: 'أوتريخت (Utrecht)' },
  { value: 'آيندهوفن', label: 'آيندهوفن (Eindhoven)' },
  { value: 'بروكسل', label: 'بروكسل (Brussels)' },
  { value: 'أنتويرب', label: 'أنتويرب (Antwerp)' },
  { value: 'غنت', label: 'غنت (Ghent)' },
  { value: 'شارلروا', label: 'شارلروا (Charleroi)' },
  { value: 'فيينا', label: 'فيينا (Vienna)' },
  { value: 'غراز', label: 'غراز (Graz)' },
  { value: 'لينز', label: 'لينز (Linz)' },
  { value: 'سالزبورغ', label: 'سالزبورغ (Salzburg)' },
  { value: 'زيورخ', label: 'زيورخ (Zurich)' },
  { value: 'جنيف', label: 'جنيف (Geneva)' },
  { value: 'بازل', label: 'بازل (Basel)' },
  { value: 'برن', label: 'برن (Bern)' },
  { value: 'لوزان', label: 'لوزان (Lausanne)' },
  { value: 'ستوكهولم', label: 'ستوكهولم (Stockholm)' },
  { value: 'غوتنبرغ', label: 'غوتنبرغ (Gothenburg)' },
  { value: 'مالمو', label: 'مالمو (Malmö)' },
  { value: 'أوسلو', label: 'أوسلو (Oslo)' },
  { value: 'برغن', label: 'برغن (Bergen)' },
  { value: 'تروندهايم', label: 'تروندهايم (Trondheim)' },
  { value: 'كوبنهاغن', label: 'كوبنهاغن (Copenhagen)' },
  { value: 'أرهوس', label: 'أرهوس (Aarhus)' },
  { value: 'أودنسه', label: 'أودنسه (Odense)' },
  { value: 'هلسنكي', label: 'هلسنكي (Helsinki)' },
  { value: 'إسبو', label: 'إسبو (Espoo)' },
  { value: 'تامبيري', label: 'تامبيري (Tampere)' },
  { value: 'فانتا', label: 'فانتا (Vantaa)' },
  { value: 'وارسو', label: 'وارسو (Warsaw)' },
  { value: 'كراكوف', label: 'كراكوف (Kraków)' },
  { value: 'لودز', label: 'لودز (Łódź)' },
  { value: 'فروتسواف', label: 'فروتسواف (Wrocław)' },
  { value: 'بوزنان', label: 'بوزنان (Poznań)' },
  { value: 'غدانسك', label: 'غدانسك (Gdańsk)' },
  { value: 'براغ', label: 'براغ (Prague)' },
  { value: 'برنو', label: 'برنو (Brno)' },
  { value: 'أوسترافا', label: 'أوسترافا (Ostrava)' },
  { value: 'بودابست', label: 'بودابست (Budapest)' },
  { value: 'دبرتسن', label: 'دبرتسن (Debrecen)' },
  { value: 'سيكشفهيرفار', label: 'سيكشفهيرفار (Székesfehérvár)' },
  { value: 'أثينا', label: 'أثينا (Athens)' },
  { value: 'سالونيك', label: 'سالونيك (Thessaloniki)' },
  { value: 'باتراس', label: 'باتراس (Patras)' },
  { value: 'لاريسا', label: 'لاريسا (Larissa)' },
  { value: 'لشبونة', label: 'لشبونة (Lisbon)' },
  { value: 'بورتو', label: 'بورتو (Porto)' },
  { value: 'أمادورا', label: 'أمادورا (Amadora)' },
  { value: 'براغا', label: 'براغا (Braga)' },
  { value: 'دبلن', label: 'دبلن (Dublin)' },
  { value: 'كورك', label: 'كورك (Cork)' },
  { value: 'ليمريك', label: 'ليمريك (Limerick)' },
  { value: 'موسكو', label: 'موسكو (Moscow)' },
  { value: 'سانت بطرسبرغ', label: 'سانت بطرسبرغ (Saint Petersburg)' },
  { value: 'نيجني نوفغورود', label: 'نيجني نوفغورود (Nizhny Novgorod)' },
  { value: 'يكاترينبورغ', label: 'يكاترينبورغ (Yekaterinburg)' },
  { value: 'قازان', label: 'قازان (Kazan)' },
  { value: 'تشيليابينسك', label: 'تشيليابينسك (Chelyabinsk)' },
  { value: 'أومسك', label: 'أومسك (Omsk)' },
  { value: 'سامارا', label: 'سامارا (Samara)' },
  { value: 'روستوف على الدون', label: 'روستوف على الدون (Rostov-on-Don)' },
  { value: 'أوفا', label: 'أوفا (Ufa)' },
  { value: 'كراسنويارسك', label: 'كراسنويارسك (Krasnoyarsk)' },
  { value: 'فورونيج', label: 'فورونيج (Voronezh)' },
  { value: 'بيرم', label: 'بيرم (Perm)' },
  { value: 'فولغوغراد', label: 'فولغوغراد (Volgograd)' },
  { value: 'كييف', label: 'كييف (Kyiv)' },
  { value: 'خاركيف', label: 'خاركيف (Kharkiv)' },
  { value: 'أوديسا', label: 'أوديسا (Odesa)' },
  { value: 'دنيبرو', label: 'دنيبرو (Dnipro)' },
  { value: 'دونيتسك', label: 'دونيتسك (Donetsk)' },
  { value: 'زابوروجيا', label: 'زابوروجيا (Zaporizhzhia)' },
  { value: 'لفيف', label: 'لفيف (Lviv)' },
  { value: 'كراماتورسك', label: 'كراماتورسك (Kramatorsk)' },
  
  // أمريكا الشمالية
  { value: 'نيويورك', label: 'نيويورك (New York)' },
  { value: 'لوس أنجلوس', label: 'لوس أنجلوس (Los Angeles)' },
  { value: 'شيكاغو', label: 'شيكاغو (Chicago)' },
  { value: 'هيوستن', label: 'هيوستن (Houston)' },
  { value: 'فينيكس', label: 'فينيكس (Phoenix)' },
  { value: 'فيلادلفيا', label: 'فيلادلفيا (Philadelphia)' },
  { value: 'سان أنطونيو', label: 'سان أنطونيو (San Antonio)' },
  { value: 'سان دييغو', label: 'سان دييغو (San Diego)' },
  { value: 'دالاس', label: 'دالاس (Dallas)' },
  { value: 'سان خوسيه', label: 'سان خوسيه (San Jose)' },
  { value: 'أوستن', label: 'أوستن (Austin)' },
  { value: 'جاكسونفيل', label: 'جاكسونفيل (Jacksonville)' },
  { value: 'سان فرانسيسكو', label: 'سان فرانسيسكو (San Francisco)' },
  { value: 'إنديانابوليس', label: 'إنديانابوليس (Indianapolis)' },
  { value: 'كولومبوس', label: 'كولومبوس (Columbus)' },
  { value: 'فورت وورث', label: 'فورت وورث (Fort Worth)' },
  { value: 'شارلوت', label: 'شارلوت (Charlotte)' },
  { value: 'سياتل', label: 'سياتل (Seattle)' },
  { value: 'دنفر', label: 'دنفر (Denver)' },
  { value: 'واشنطن', label: 'واشنطن (Washington)' },
  { value: 'بوسطن', label: 'بوسطن (Boston)' },
  { value: 'إل باسو', label: 'إل باسو (El Paso)' },
  { value: 'ديترويت', label: 'ديترويت (Detroit)' },
  { value: 'ناشفيل', label: 'ناشفيل (Nashville)' },
  { value: 'بورتلاند', label: 'بورتلاند (Portland)' },
  { value: 'أوكلاهوما سيتي', label: 'أوكلاهوما سيتي (Oklahoma City)' },
  { value: 'لاس فيغاس', label: 'لاس فيغاس (Las Vegas)' },
  { value: 'ممفيس', label: 'ممفيس (Memphis)' },
  { value: 'لويزفيل', label: 'لويزفيل (Louisville)' },
  { value: 'بالتيمور', label: 'بالتيمور (Baltimore)' },
  { value: 'ميلووكي', label: 'ميلووكي (Milwaukee)' },
  { value: 'ألبوكيركي', label: 'ألبوكيركي (Albuquerque)' },
  { value: 'توسان', label: 'توسان (Tucson)' },
  { value: 'فريسنو', label: 'فريسنو (Fresno)' },
  { value: 'ساكرامنتو', label: 'ساكرامنتو (Sacramento)' },
  { value: 'كانساس سيتي', label: 'كانساس سيتي (Kansas City)' },
  { value: 'ميسا', label: 'ميسا (Mesa)' },
  { value: 'أتلانتا', label: 'أتلانتا (Atlanta)' },
  { value: 'أوماها', label: 'أوماها (Omaha)' },
  { value: 'كولورادو سبرينغز', label: 'كولورادو سبرينغز (Colorado Springs)' },
  { value: 'رالي', label: 'رالي (Raleigh)' },
  { value: 'ميامي', label: 'ميامي (Miami)' },
  { value: 'لونج بيتش', label: 'لونج بيتش (Long Beach)' },
  { value: 'فيرجينيا بيتش', label: 'فيرجينيا بيتش (Virginia Beach)' },
  { value: 'أوكلاند', label: 'أوكلاند (Oakland)' },
  { value: 'مينيابوليس', label: 'مينيابوليس (Minneapolis)' },
  { value: 'تولسا', label: 'تولسا (Tulsa)' },
  { value: 'كليفلاند', label: 'كليفلاند (Cleveland)' },
  { value: 'ويشيتا', label: 'ويشيتا (Wichita)' },
  { value: 'أرلينغتون', label: 'أرلينغتون (Arlington)' },
  { value: 'نيو أورليانز', label: 'نيو أورليانز (New Orleans)' },
  { value: 'هونولولو', label: 'هونولولو (Honolulu)' },
  { value: 'تامبا', label: 'تامبا (Tampa)' },
  { value: 'أورلاندو', label: 'أورلاندو (Orlando)' },
  { value: 'سانت بيترسبرغ', label: 'سانت بيترسبرغ (St. Petersburg)' },
  { value: 'سينسيناتي', label: 'سينسيناتي (Cincinnati)' },
  { value: 'بيتسبرغ', label: 'بيتسبرغ (Pittsburgh)' },
  { value: 'سانت لويس', label: 'سانت لويس (St. Louis)' },
  { value: 'توليدو', label: 'توليدو (Toledo)' },
  { value: 'غرينزبورو', label: 'غرينزبورو (Greensboro)' },
  { value: 'بافالو', label: 'بافالو (Buffalo)' },
  { value: 'نيوارك', label: 'نيوارك (Newark)' },
  { value: 'بالتيمور', label: 'بالتيمور (Baltimore)' },
  { value: 'تورونتو', label: 'تورونتو (Toronto)' },
  { value: 'مونتريال', label: 'مونتريال (Montreal)' },
  { value: 'فانكوفر', label: 'فانكوفر (Vancouver)' },
  { value: 'أوتاوا', label: 'أوتاوا (Ottawa)' },
  { value: 'كالغاري', label: 'كالغاري (Calgary)' },
  { value: 'إدمونتون', label: 'إدمونتون (Edmonton)' },
  { value: 'وينيبيغ', label: 'وينيبيغ (Winnipeg)' },
  { value: 'كيبيك', label: 'كيبيك (Quebec City)' },
  { value: 'هاميلتون', label: 'هاميلتون (Hamilton)' },
  { value: 'كيتشنر', label: 'كيتشنر (Kitchener)' },
  { value: 'لندن', label: 'لندن - كندا (London)' },
  { value: 'هاليفاكس', label: 'هاليفاكس (Halifax)' },
  { value: 'فيكتوريا', label: 'فيكتوريا (Victoria)' },
  { value: 'مدينة مكسيكو', label: 'مدينة مكسيكو (Mexico City)' },
  { value: 'غوادالاخارا', label: 'غوادالاخارا (Guadalajara)' },
  { value: 'مونتيري', label: 'مونتيري (Monterrey)' },
  { value: 'بويبلا', label: 'بويبلا (Puebla)' },
  { value: 'تيخوانا', label: 'تيخوانا (Tijuana)' },
  { value: 'ليون', label: 'ليون - المكسيك (León)' },
  { value: 'خواريز', label: 'خواريز (Juárez)' },
  { value: 'توريون', label: 'توريون (Torreón)' },
  { value: 'كويريتارو', label: 'كويريتارو (Querétaro)' },
  { value: 'سان لويس بوتوسي', label: 'سان لويس بوتوسي (San Luis Potosí)' },
  { value: 'ميريدا', label: 'ميريدا (Mérida)' },
  { value: 'مكسيكالي', label: 'مكسيكالي (Mexicali)' },
  { value: 'أغواسكاليينتس', label: 'أغواسكاليينتس (Aguascalientes)' },
  { value: 'تولوكا', label: 'تولوكا (Toluca)' },
  { value: 'كوليما', label: 'كوليما (Cuernavaca)' },
  { value: 'أكابولكو', label: 'أكابولكو (Acapulco)' },
  { value: 'كانكون', label: 'كانكون (Cancún)' },
  { value: 'هافانا', label: 'هافانا (Havana)' },
  { value: 'سانتياغو دي كوبا', label: 'سانتياغو دي كوبا (Santiago de Cuba)' },
  { value: 'سان خوسيه', label: 'سان خوسيه - كوستاريكا (San José)' },
  { value: 'بنما سيتي', label: 'بنما سيتي (Panama City)' },
  { value: 'سانتو دومينغو', label: 'سانتو دومينغو (Santo Domingo)' },
  { value: 'بورت أو برنس', label: 'بورت أو برنس (Port-au-Prince)' },
  { value: 'كينغستون', label: 'كينغستون (Kingston)' },
  { value: 'سان خوان', label: 'سان خوان (San Juan)' },
  
  // أمريكا الجنوبية
  { value: 'ساو باولو', label: 'ساو باولو (São Paulo)' },
  { value: 'ريو دي جانيرو', label: 'ريو دي جانيرو (Rio de Janeiro)' },
  { value: 'برازيليا', label: 'برازيليا (Brasília)' },
  { value: 'سلفادور', label: 'سلفادور (Salvador)' },
  { value: 'فورتاليزا', label: 'فورتاليزا (Fortaleza)' },
  { value: 'بيلو هوريزونتي', label: 'بيلو هوريزونتي (Belo Horizonte)' },
  { value: 'ماناوس', label: 'ماناوس (Manaus)' },
  { value: 'كوريتيبا', label: 'كوريتيبا (Curitiba)' },
  { value: 'ريسيفي', label: 'ريسيفي (Recife)' },
  { value: 'بورتو أليغري', label: 'بورتو أليغري (Porto Alegre)' },
  { value: 'بيلém', label: 'بيلém (Belém)' },
  { value: 'غويانيا', label: 'غويانيا (Goiânia)' },
  { value: 'غوارولوس', label: 'غوارولوس (Guarulhos)' },
  { value: 'كامبيناس', label: 'كامبيناس (Campinas)' },
  { value: 'ساو غونسالو', label: 'ساو غونسالو (São Gonçalo)' },
  { value: 'نوفا إيغواسو', label: 'نوفا إيغواسو (Nova Iguaçu)' },
  { value: 'ساو لويس', label: 'ساو لويس (São Luís)' },
  { value: 'ماسايو', label: 'ماسايو (Maceió)' },
  { value: 'ناتال', label: 'ناتال (Natal)' },
  { value: 'جوانا بيساو', label: 'جوانا بيساو (João Pessoa)' },
  { value: 'أراكاجو', label: 'أراكاجو (Aracaju)' },
  { value: 'فلوريانوبوليس', label: 'فلوريانوبوليس (Florianópolis)' },
  { value: 'فيتوريا', label: 'فيتوريا (Vitória)' },
  { value: 'كويابا', label: 'كويابا (Cuiabá)' },
  { value: 'كامبو غراندي', label: 'كامبو غراندي (Campo Grande)' },
  { value: 'بوينس آيرس', label: 'بوينس آيرس (Buenos Aires)' },
  { value: 'قرطبة', label: 'قرطبة (Córdoba)' },
  { value: 'روزاريو', label: 'روزاريو (Rosario)' },
  { value: 'ميندوزا', label: 'ميندوزا (Mendoza)' },
  { value: 'سان ميغيل دي توكومان', label: 'سان ميغيل دي توكومان (San Miguel de Tucumán)' },
  { value: 'لابلاتا', label: 'لابلاتا (La Plata)' },
  { value: 'مار ديل بلاتا', label: 'مار ديل بلاتا (Mar del Plata)' },
  { value: 'سانتا في', label: 'سانتا في (Santa Fe)' },
  { value: 'سان خوان', label: 'سان خوان - الأرجنتين (San Juan)' },
  { value: 'ريسيتنسيا', label: 'ريسيتنسيا (Resistencia)' },
  { value: 'ليما', label: 'ليما (Lima)' },
  { value: 'أريكويبا', label: 'أريكويبا (Arequipa)' },
  { value: 'تروخيو', label: 'تروخيو (Trujillo)' },
  { value: 'شيمبوتي', label: 'شيمبوتي (Chimbote)' },
  { value: 'بيورا', label: 'بيورا (Piura)' },
  { value: 'إيكيتوس', label: 'إيكيتوس (Iquitos)' },
  { value: 'كوسكو', label: 'كوسكو (Cusco)' },
  { value: 'سانتياغو', label: 'سانتياغو (Santiago)' },
  { value: 'فالبارايسو', label: 'فالبارايسو (Valparaíso)' },
  { value: 'كونسيبسيون', label: 'كونسيبسيون (Concepción)' },
  { value: 'لا سيرينا', label: 'لا سيرينا (La Serena)' },
  { value: 'أنتوفاغاستا', label: 'أنتوفاغاستا (Antofagasta)' },
  { value: 'بوغوتا', label: 'بوغوتا (Bogotá)' },
  { value: 'ميديلين', label: 'ميديلين (Medellín)' },
  { value: 'كالي', label: 'كالي (Cali)' },
  { value: 'بارانكيا', label: 'بارانكيا (Barranquilla)' },
  { value: 'قرطاجنة', label: 'قرطاجنة (Cartagena)' },
  { value: 'كويتو', label: 'كويتو (Cúcuta)' },
  { value: 'بوكارامانغا', label: 'بوكارامانغا (Bucaramanga)' },
  { value: 'بيريرا', label: 'بيريرا (Pereira)' },
  { value: 'سانتا مارتا', label: 'سانتا مارتا (Santa Marta)' },
  { value: 'مانيزاليس', label: 'مانيزاليس (Manizales)' },
  { value: 'كاراكاس', label: 'كاراكاس (Caracas)' },
  { value: 'ماراكايبو', label: 'ماراكايبو (Maracaibo)' },
  { value: 'فالنسيا', label: 'فالنسيا - فنزويلا (Valencia)' },
  { value: 'باركيسيميتو', label: 'باركيسيميتو (Barquisimeto)' },
  { value: 'سيوداد غوايانا', label: 'سيوداد غوايانا (Ciudad Guayana)' },
  { value: 'كيتو', label: 'كيتو (Quito)' },
  { value: 'غواياكيل', label: 'غواياكيل (Guayaquil)' },
  { value: 'كوينكا', label: 'كوينكا (Cuenca)' },
  { value: 'سانتو دومينغو', label: 'سانتو دومينغو - الإكوادور (Santo Domingo)' },
  { value: 'ماشالا', label: 'ماشالا (Machala)' },
  { value: 'مونتيفيديو', label: 'مونتيفيديو (Montevideo)' },
  { value: 'سالتو', label: 'سالتو (Salto)' },
  { value: 'بايساندو', label: 'بايساندو (Paysandú)' },
  { value: 'أسونسيون', label: 'أسونسيون (Asunción)' },
  { value: 'سيوداد ديل إيستي', label: 'سيوداد ديل إيستي (Ciudad del Este)' },
  { value: 'لاباز', label: 'لاباز (La Paz)' },
  { value: 'سانتا كروز دي لا سييرا', label: 'سانتا كروز دي لا سييرا (Santa Cruz de la Sierra)' },
  { value: 'كوتشابامبا', label: 'كوتشابامبا (Cochabamba)' },
  { value: 'سوكري', label: 'سوكري (Sucre)' },
  { value: 'أورورو', label: 'أورورو (Oruro)' },
  { value: 'بوتوسي', label: 'بوتوسي (Potosí)' },
    // السعودية
  { value: 'الرياض', label: 'الرياض (Riyadh)' },
  { value: 'جدة', label: 'جدة (Jeddah)' },
  { value: 'مكة المكرمة', label: 'مكة المكرمة (Makkah)' },
  { value: 'المدينة المنورة', label: 'المدينة المنورة (Madinah)' },
  { value: 'الدمام', label: 'الدمام (Dammam)' },
  { value: 'الخبر', label: 'الخبر (Al Khobar)' },
  { value: 'الطائف', label: 'الطائف (Taif)' },
  { value: 'بريدة', label: 'بريدة (Buraydah)' },
  { value: 'تبوك', label: 'تبوك (Tabuk)' },
  { value: 'خميس مشيط', label: 'خميس مشيط (Khamis Mushait)' },
  { value: 'حائل', label: 'حائل (Hail)' },
  { value: 'نجران', label: 'نجران (Najran)' },
  { value: 'جازان', label: 'جازان (Jazan)' },
  { value: 'أبها', label: 'أبها (Abha)' },
  { value: 'ينبع', label: 'ينبع (Yanbu)' },
  { value: 'سكاكا', label: 'سكاكا (Sakaka)' },
  { value: 'عرعر', label: 'عرعر (Arar)' },
  { value: 'الباحة', label: 'الباحة (Al Baha)' },
  { value: 'الخرج', label: 'الخرج (Al-Kharj)' },
  { value: 'الدرعية', label: 'الدرعية (Ad Diriyah)' },
  { value: 'المجمعة', label: 'المجمعة (Al Majma\'ah)' },
  { value: 'الزلفي', label: 'الزلفي (Al Zulfi)' },
  { value: 'الدوادمي', label: 'الدوادمي (Ad Dawadimi)' },
  { value: 'وادي الدواسر', label: 'وادي الدواسر (Wadi Ad Dawasir)' },
  { value: 'عفيف', label: 'عفيف (Afif)' },
  { value: 'القويعية', label: 'القويعية (Al Quway\'iyah)' },
  { value: 'شقراء', label: 'شقراء (Shaqra)' },
  { value: 'حوطة بني تميم', label: 'حوطة بني تميم (Hotat Bani Tamim)' },
  { value: 'رابغ', label: 'رابغ (Rabigh)' },
  { value: 'القنفذة', label: 'القنفذة (Al Qunfudhah)' },
  { value: 'الليث', label: 'الليث (Al Lith)' },
  { value: 'خليص', label: 'خليص (Khulais)' },
  { value: 'رنية', label: 'رنية (Ranyah)' },
  { value: 'تربة', label: 'تربة (Turabah)' },
  { value: 'الظهران', label: 'الظهران (Dhahran)' },
  { value: 'الأحساء', label: 'الأحساء (Al Ahsa)' },
  { value: 'الهفوف', label: 'الهفوف (Al Hufuf)' },
  { value: 'المبرز', label: 'المبرز (Al Mubarraz)' },
  { value: 'الجبيل', label: 'الجبيل (Jubail)' },
  { value: 'حفر الباطن', label: 'حفر الباطن (Hafr Al Batin)' },
  { value: 'الخفجي', label: 'الخفجي (Al Khafji)' },
  { value: 'رأس تنورة', label: 'رأس تنورة (Ras Tanura)' },
  { value: 'القطيف', label: 'القطيف (Qatif)' },
  { value: 'بقيق', label: 'بقيق (Abqaiq)' },
  { value: 'النعيرية', label: 'النعيرية (Nairiyah)' },
  { value: 'قرية العليا', label: 'قرية العليا (Qaryat Al Ulya)' },
  { value: 'عنيزة', label: 'عنيزة (Unaizah)' },
  { value: 'الرس', label: 'الرس (Ar Rass)' },
  { value: 'البكيرية', label: 'البكيرية (Al Bukayriyah)' },
  { value: 'البدائع', label: 'البدائع (Al Badaye)' },
  { value: 'المذنب', label: 'المذنب (Al Mithnab)' },
  { value: 'رياض الخبراء', label: 'رياض الخبراء (Riyad Al Khabra)' },
  { value: 'بيشة', label: 'بيشة (Bisha)' },
  { value: 'محايل عسير', label: 'محايل عسير (Mahayil)' },
  { value: 'النماص', label: 'النماص (Al Namas)' },
  { value: 'تنومة', label: 'تنومة (Tanomah)' },
  { value: 'أحد رفيدة', label: 'أحد رفيدة (Ahad Rafidah)' },
  { value: 'سراة عبيدة', label: 'سراة عبيدة (Sarat Abidah)' },
  { value: 'بلقرن', label: 'بلقرن (Balqarn)' },
  { value: 'ضباء', label: 'ضباء (Duba)' },
  { value: 'الوجه', label: 'الوجه (Al Wajh)' },
  { value: 'أملج', label: 'أملج (Umluj)' },
  { value: 'تيماء', label: 'تيماء (Tayma)' },
  { value: 'حقل', label: 'حقل (Haqi)' },
  { value: 'بقعاء', label: 'بقعاء (Baqa)' },
  { value: 'الغزالة', label: 'الغزالة (Al Ghazalah)' },
  { value: 'رفحاء', label: 'رفحاء (Rafha)' },
  { value: 'طريف', label: 'طريف (Turaif)' },
  { value: 'صبيا', label: 'صبيا (Sabya)' },
  { value: 'أبو عريش', label: 'أبو عريش (Abu Arish)' },
  { value: 'صامطة', label: 'صامطة (Samtah)' },
  { value: 'بيش', label: 'بيش (Baish)' },
  { value: 'الدرب', label: 'الدرب (Ad Darb)' },
  { value: 'العارضة', label: 'العارضة (Al Aridah)' },
  { value: 'فيفاء', label: 'فيفاء (Fifa)' },
  { value: 'شرورة', label: 'شرورة (Sharurah)' },
  { value: 'حبونا', label: 'حبونا (Hubuna)' },
  { value: 'بلجرشي', label: 'بلجرشي (Baljurashi)' },
  { value: 'المندق', label: 'المندق (Al Mandq)' },
  { value: 'المخواة', label: 'المخواة (Al Makhwah)' },
  { value: 'قلوة', label: 'قلوة (Qilwah)' },
  { value: 'دومة الجندل', label: 'دومة الجندل (Dumat Al Jandal)' },
  { value: 'القريات', label: 'القريات (Al Qurayyat)' },
  { value: 'طبرجل', label: 'طبرجل (Tabarjal)' },
  { value: 'العلا', label: 'العلا (Al Ula)' },
  { value: 'بدر', label: 'بدر (Badr)' },
  { value: 'الحناكية', label: 'الحناكية (Al Hinakiyah)' },
  { value: 'مهد الذهب', label: 'مهد الذهب (Mahd Al Dhahab)' },
  
  // أستراليا وأوقيانوسيا
  { value: 'سيدني', label: 'سيدني (Sydney)' },
  { value: 'ميلبورن', label: 'ميلبورن (Melbourne)' },
  { value: 'بريسبان', label: 'بريسبان (Brisbane)' },
  { value: 'بيرث', label: 'بيرث (Perth)' },
  { value: 'أديلايد', label: 'أديلايد (Adelaide)' },
  { value: 'كانبرا', label: 'كانبرا (Canberra)' },
  { value: 'داروين', label: 'داروين (Darwin)' },
  { value: 'هوبارت', label: 'هوبارت (Hobart)' },
  { value: 'جولد كوست', label: 'جولد كوست (Gold Coast)' },
  { value: 'نيوكاسل', label: 'نيوكاسل (Newcastle)' },
  { value: 'ولونغونغ', label: 'ولونغونغ (Wollongong)' },
  { value: 'جيلونغ', label: 'جيلونغ (Geelong)' },
  { value: 'تاونسفيل', label: 'تاونسفيل (Townsville)' },
  { value: 'كيرنز', label: 'كيرنز (Cairns)' },
  { value: 'توومبا', label: 'توومبا (Toowoomba)' },
  { value: 'بالارات', label: 'بالارات (Ballarat)' },
  { value: 'بنديجو', label: 'بنديجو (Bendigo)' },
  { value: 'ألبري', label: 'ألبري (Albury)' },
  { value: 'أوكلاند', label: 'أوكلاند - نيوزيلندا (Auckland)' },
  { value: 'ويلينغتون', label: 'ويلينغتون (Wellington)' },
  { value: 'كرايستشيرش', label: 'كرايستشيرش (Christchurch)' },
  { value: 'هاميلتون', label: 'هاميلتون - نيوزيلندا (Hamilton)' },
  { value: 'دنيدن', label: 'دنيدن (Dunedin)' },
  { value: 'تاورانغا', label: 'تاورانغا (Tauranga)' },
  { value: 'بالمرستون نورث', label: 'بالمرستون نورث (Palmerston North)' },
  { value: 'نابير', label: 'نابير (Napier)' },
  { value: 'روتوروا', label: 'روتوروا (Rotorua)' },
  { value: 'نيوبلايموث', label: 'نيوبلايموث (New Plymouth)' },
  { value: 'إنفركارجيل', label: 'إنفركارجيل (Invercargill)' },
  { value: 'بابيتي', label: 'بابيتي (Papeete)' },
  { value: 'نوميا', label: 'نوميا (Nouméa)' },
  { value: 'سوفا', label: 'سوفا (Suva)' },
  { value: 'بورت مورسبي', label: 'بورت مورسبي (Port Moresby)' },
  { value: 'هونيارا', label: 'هونيارا (Honiara)' },
  { value: 'أبيان', label: 'أبيان (Apia)' },
  { value: 'نوكو ألوفا', label: 'نوكو ألوفا (Nuku\'alofa)' },
];

interface CityAutocompleteProps {
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
  className?: string;
  error?: string;
}

const CityAutocomplete: React.FC<CityAutocompleteProps> = ({
  value,
  onChange,
  placeholder = 'ابحث عن مدينة',
  className = '',
  error
}) => {
  const selectedOption = useMemo(() => {
    if (!value) return null;
    const found = worldCities.find(city => city.value === value);
    // إذا لم تكن المدينة في القائمة، نعيدها كخيار مخصص
    if (!found && value.trim()) {
      return { value: value, label: value };
    }
    return found || null;
  }, [value]);

  const handleChange = (selectedOption: any) => {
    onChange(selectedOption ? selectedOption.value : '');
  };

  const customStyles = {
    control: (provided: any, state: any) => ({
      ...provided,
      border: error ? '1px solid #ef4444' : '1px solid #d1d5db',
      borderRadius: '0.375rem',
      padding: '0.25rem',
      textAlign: 'right' as const,
      '&:hover': {
        border: error ? '1px solid #ef4444' : '1px solid #9ca3af',
      },
      boxShadow: state.isFocused ? (error ? '0 0 0 1px #ef4444' : '0 0 0 1px #115e59') : 'none',
    }),
    menu: (provided: any) => ({
      ...provided,
      textAlign: 'right' as const,
      zIndex: 9999,
    }),
    option: (provided: any, state: any) => ({
      ...provided,
      textAlign: 'right' as const,
      backgroundColor: state.isSelected
        ? '#115e59'
        : state.isFocused
        ? '#f0fdfa'
        : 'white',
      color: state.isSelected ? 'white' : '#1f2937',
      '&:hover': {
        backgroundColor: state.isSelected ? '#115e59' : '#f0fdfa',
      },
    }),
    singleValue: (provided: any) => ({
      ...provided,
      textAlign: 'right' as const,
      direction: 'rtl' as const,
    }),
    input: (provided: any) => ({
      ...provided,
      textAlign: 'right' as const,
      direction: 'rtl' as const,
    }),
    placeholder: (provided: any) => ({
      ...provided,
      textAlign: 'right' as const,
      direction: 'rtl' as const,
    }),
  };

  return (
    <div className="flex flex-col">
      <Select
        value={selectedOption}
        onChange={handleChange}
        options={worldCities}
        placeholder={placeholder}
        isClearable
        isSearchable
        className={className}
        styles={customStyles}
        dir="rtl"
        noOptionsMessage={() => 'لا توجد نتائج'}
        loadingMessage={() => 'جاري البحث...'}
        filterOption={(option, inputValue) => {
          if (!inputValue) return true;
          const searchTerm = inputValue.toLowerCase();
          const label = option.label.toLowerCase();
          const value = option.value.toLowerCase();
          return label.includes(searchTerm) || value.includes(searchTerm);
        }}
      />
      {error && (
        <p className="text-red-500 text-sm mt-1 text-right">{error}</p>
      )}
    </div>
  );
};

export default CityAutocomplete;

