export const saudiCitiesMap: { [key: string]: string } = {
  'Riyadh': 'الرياض',
  'Al-Kharj': 'الخرج',
  'Al Kharj': 'الخرج',
  'Ad Diriyah': 'الدرعية',
  'Diriyah': 'الدرعية',
  'Al Majma\'ah': 'المجمعة',
  'Al Majmaah': 'المجمعة',
  'Al Zulfi': 'الزلفي',
  'Ad Dawadimi': 'الدوادمي',
  'Dawadmi': 'الدوادمي',
  'Wadi Ad Dawasir': 'وادي الدواسر',
  'Wadi Al Dawasir': 'وادي الدواسر',
  'Afif': 'عفيف',
  'Al Quway\'iyah': 'القويعية',
  'Al Quwayiyah': 'القويعية',
  'Shaqra': 'شقراء',
  'Hotat Bani Tamim': 'حوطة بني تميم',
  'Makkah': 'مكة المكرمة',
  'Mecca': 'مكة المكرمة',
  'Jeddah': 'جدة',
  'Taif': 'الطائف',
  'Rabigh': 'رابغ',
  'Al Qunfudhah': 'القنفذة',
  'Al Lith': 'الليث',
  'Khulais': 'خليص',
  'Ranyah': 'رنية',
  'Turabah': 'تربة',
  'Madinah': 'المدينة المنورة',
  'Medina': 'المدينة المنورة',
  'Yanbu': 'ينبع',
  'Al Ula': 'العلا',
  'Badr': 'بدر',
  'Al Hinakiyah': 'الحناكية',
  'Mahd Al Dhahab': 'مهد الذهب',
  'Dammam': 'الدمام',
  'Al Khobar': 'الخبر',
  'Khobar': 'الخبر',
  'Dhahran': 'الظهران',
  'Al Ahsa': 'الأحساء',
  'Ahsa': 'الأحساء',
  'Al Hufuf': 'الهفوف',
  'Hufuf': 'الهفوف',
  'Al Mubarraz': 'المبرز',
  'Jubail': 'الجبيل',
  'Hafr Al Batin': 'حفر الباطن',
  'Al Khafji': 'الخفجي',
  'Ras Tanura': 'رأس تنورة',
  'Qatif': 'القطيف',
  'Abqaiq': 'بقيق',
  'Nairiyah': 'النعيرية',
  'Qaryat Al Ulya': 'قرية العليا',
  'Buraydah': 'بريدة',
  'Unaizah': 'عنيزة',
  'Ar Rass': 'الرس',
  'Rass': 'الرس',
  'Al Bukayriyah': 'البكيرية',
  'Al Badaye': 'البدائع',
  'Al Mithnab': 'المذنب',
  'Riyad Al Khabra': 'رياض الخبراء',
  'Abha': 'أبها',
  'Khamis Mushait': 'خميس مشيط',
  'Bisha': 'بيشة',
  'Mahayil': 'محايل عسير',
  'Mahayil Asir': 'محايل عسير',
  'Al Namas': 'النماص',
  'Tanomah': 'تنومة',
  'Ahad Rafidah': 'أحد رفيدة',
  'Sarat Abidah': 'سراة عبيدة',
  'Balqarn': 'بلقرن',
  'Tabuk': 'تبوك',
  'Duba': 'ضباء',
  'Al Wajh': 'الوجه',
  'Umluj': 'أملج',
  'Tayma': 'تيماء',
  'Haqi': 'حقل',
  'Haql': 'حقل',
  'Hail': 'حائل',
  'Baqa': 'بقعاء',
  'Al Ghazalah': 'الغزالة',
  'Arar': 'عرعر',
  'Rafha': 'رفحاء',
  'Turaif': 'طريف',
  'Jazan': 'جازان',
  'Jizan': 'جازان',
  'Sabya': 'صبيا',
  'Abu Arish': 'أبو عريش',
  'Samtah': 'صامطة',
  'Baish': 'بيش',
  'Ad Darb': 'الدرب',
  'Al Aridah': 'العارضة',
  'Fifa': 'فيفاء',
  'Najran': 'نجران',
  'Sharurah': 'شرورة',
  'Hubuna': 'حبونا',
  'Al Baha': 'الباحة',
  'Baha': 'الباحة',
  'Baljurashi': 'بلجرشي',
  'Al Mandq': 'المندق',
  'Al Makhwah': 'المخواة',
  'Qilwah': 'قلوة',
  'Sakaka': 'سكاكا',
  'Dumat Al Jandal': 'دومة الجندل',
  'Al Qurayyat': 'القريات',
  'Qurayyat': 'القريات',
  'Tabarjal': 'طبرجل',
};

/**
 * دالة لتحويل اسم المدينة إلى العربية إذا كان مسجلاً بالإنجليزية
 */
export function formatSaudiCity(cityName: string | null | undefined): string {
  if (!cityName) return '';
  const trimmed = String(cityName).trim();
  if (saudiCitiesMap[trimmed]) {
    return saudiCitiesMap[trimmed];
  }
  // Case-insensitive fallback
  const lower = trimmed.toLowerCase();
  for (const [enKey, arVal] of Object.entries(saudiCitiesMap)) {
    if (enKey.toLowerCase() === lower) {
      return arVal;
    }
  }
  return trimmed;
}
