// دالة لتحويل pageRoute إلى عنوان عربي
export function getPageTitleArabic(pageRoute: string | undefined): string {
  if (!pageRoute) return '';
  
  // استخراج المسار من URL الكامل
  let path = pageRoute;
  try {
    const urlObj = new URL(pageRoute);
    path = urlObj.pathname;
  } catch {
    path = pageRoute;
  }
  
  // خريطة المسارات إلى العناوين العربية
  const pageTitles: Record<string, string> = {
    '/admin/home': 'الرئيسية',
    '/admin/neworders': 'طلبات جديدة',
    '/admin/currentorderstest': 'الطلبات الحالية',
    '/admin/endedorders': 'الطلبات المكتملة',
    '/admin/clients': 'قائمة العملاء',
    '/admin/fulllist': 'قائمة العاملات',
    '/admin/availablelist': 'العاملات المتاحات',
    '/admin/bookedlist': 'العاملات المحجوزات',
    '/admin/newhomemaids': 'إضافة عاملة جديدة',
    '/admin/homemaidinfo': 'معلومات العاملة',
    '/admin/housedarrivals': 'التسكين',
    '/admin/checkedtable': 'الاعاشات',
    '/admin/arrival-list': 'الوصول',
    '/admin/deparatures': 'المغادرة الداخلية',
    '/admin/deparaturesfromsaudi': 'المغادرة الخارجية',
    '/admin/notifications': 'الاشعارات',
    '/admin/reportsconverted': 'التقارير',
    '/admin/templates': 'القوالب',
    '/admin/messages': 'قائمة المراسلات',
    '/admin/email-list': 'قائمة البريد الالكتروني',
    '/admin/foreign_offices_financial': 'كشف حساب المكاتب الخارجية',
    '/admin/client-accounts': 'كشف حساب العملاء',
    '/admin/employee_cash': 'كشف حساب الموظفين',
    '/admin/musanad_finacial': 'التقرير المالي لمساند',
    '/admin/settlement': 'التسوية المالية',
    '/admin/taxation': 'الاقرارات الضريبية',
    '/admin/employees': 'الموظفين',
    '/admin/incomestatments-updated': 'قائمة الدخل',
    '/admin/account-systemlogs': 'سجل النظام المحاسبي',
    '/admin/pdf-processor': 'New CV',
    '/admin/automaticpreview': 'CV Generated BY AI',
    '/admin/systemlogs': 'سجل العمليات',
    '/admin/authorizations': 'المستخدمين',
    '/admin/personal_page': 'الملف الشخصي',
    '/admin/complaints': 'الشكاوى',
    '/admin/categories': 'إدارة الفئات',
    '/admin/track_order': 'تتبع طلب',
  };
  
  // البحث عن المسار المطابق
  for (const [route, title] of Object.entries(pageTitles)) {
    if (path.includes(route)) {
      return title;
    }
  }
  
  // إذا لم يتم العثور على عنوان، إرجاع المسار
  return path;
}












